### ISSUE TITLE
Configure login component and login service for verification

### ISSUE THREAD

**Issue by nearly-trinity** [CSCI-3321-Software-Engineering/iron-man#12]
Create necessary functions for handling logins

** TODO

- [x] Update login html file to use ngForm and update input fields as ngModel
- [x] Specify (ngSubmit) attribute action
    - [x] Should call checkLogin() function inside of login.component.ts

- [x] Flesh out checkLogin() function in login.component.ts
    - [x] Pass username and password into service subscription 
    
- [x] Complete validateLogin() function in login.service.ts
    - [x] Make post request to new Express /login endpoint
    - [x] accept username and password strings as function arguments
