### ISSUE TITLE
Set up angular routing in connection with login verification

### ISSUE THREAD

**Issue by nearly-trinity** [CSCI-3321-Software-Engineering/iron-man#14]
Add implementation for the server to auto-redirect the user to the correct landing page on login

Prerequisites: Need to first complete all 3 landing pages

** TODO

- [ ] Get custom redirect URLs for each landing page
- [ ] Add pages to the Angular page router
- [ ] Attach routes to login verification functions
