### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by nearly-trinity** [CSCI-3321-Software-Engineering/iron-man#2]
** TODO
- [x] Create component for login page
- [x] Create service for handling login
- [x] Add path to routes
- [x] HTML For login page
- [x] CSS For login page
